services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 7878:7878
    volumes:
      - radarr:/config
      - /mnt:/mnt:rshared

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 8989:8989
    volumes:
      - sonarr:/config
      - /mnt:/mnt:rshared

  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    hostname: rdtclient
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 6500:6500
    volumes:
      - rdtclient:/data/db
      - /mnt:/mnt:rshared

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    hostname: overseerr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 5055:5055
    volumes:
      - overseerr:/config

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 9696:9696
    volumes:
      - prowlarr:/config

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - plex:/config
      - /mnt:/mnt:rshared

  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: zurg
    hostname: zurg
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    ports:
      - 9999:9999
    volumes:
      - zurg:/app/data
      - /var/lib/docker/volumes/root_zurg/_data/app/config.yml:/app/config.yml
      - /var/lib/docker/volumes/root_zurg/_data/app/plex_update.sh:/app/plex_update.sh

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    hostname: rclone
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    networks:
      - network
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    volumes:
      - rclone:/config/rclone
      - /mnt:/mnt:rshared
      - /var/lib/docker/volumes/root_rclone/_data/rclone.conf:/config/rclone/rclone.conf
    links:
      - zurg
    command: "mount zurg: /mnt/realdebrid --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"

networks:
  network:

volumes:
  portainer:
  radarr:
  sonarr:
  rdtclient:
  overseerr:
  prowlarr:
  plex:
  zurg:
  rclone:
